[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "cd ~/Imagens/"
desc = "Ir para a pasta Imagens"

[[mgr.prepend_keymap]]
on   = [ "<Right>" ]
run  = "plugin fast-enter"
desc = "Enter the subfolder faster, or open the file directly"


